# Generated by Django 3.0.2 on 2020-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('role', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('salary_range_from', models.FloatField()),
                ('salary_range_to', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('required_skills', models.CharField(max_length=255)),
                ('perks', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=200)),
                ('validation_key', models.CharField(max_length=10)),
            ],
        ),
    ]
