# Generated by Django 3.0.2 on 2020-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200120_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allposts',
            name='date_posted',
            field=models.DateTimeField(blank=True),
        ),
    ]
